### ISSUE TITLE
Data from K.R.

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#1]
Some of the data from K.R. has a specific naming scheme and some properties could probably be merged:

- `place_town_syl`, `place_town_py` and `place_town_ch` could be merged as `place_town` and the objects could have different lang tags (resp. `zh-Hans`, `zh-Latn-pinyin` and `zh-Hant` I guess)
- `place_prov_py` and `place_dist_py` could be renamed as `placeProvince` and `placeDistrict`

**Comment by eroux** [comment]
also `place_name_kr` and `place_name_lex` could probably disapear in favor of just `name`, with an annotation about the provenance?

**Comment by xristy** [comment]
I've moved this chaff to the admin ns for now so that it is migrated for now.
