### ISSUE TITLE
Outlines may have malformed descriptions

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/owl-schema#10]
In several outlines the <o:description type="..."/> is represented in the content of the element instead of the @type, for example in O4JW333:

    <outline:description type="location">vol:1,ff.1r-311r(pp.1-621)</outline:description>
    <outline:description type="authorship">
    t. Sarvajñādeva (k); Vidyākaraprabha; Dharmākara (ka0; Dpal gyi lhun po; r. Vidyākaraprabha; Dpal brtsegs
    </outline:description>
    <outline:description>sde dge number 1</outline:description>
    <outline:description>stog number 1</outline:description>
    <outline:description>snar thang number 1</outline:description>
    <outline:description>lha sa number 1</outline:description>
    <outline:description>urga number 1</outline:description>
    <outline:description type="toh">1</outline:description>
    <outline:description type="sde dge number">1</outline:description>

this also illustrates duplication of the `sde dge number`.

**Comment by eroux** [comment]
interesting...

**Comment by eroux** [comment]
(perhaps this kind of issue should go to [xmltoldmigration](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/issues) as it's not about the schema per se?)
