### ISSUE TITLE
place event affiliation

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#12]
In the [current schema](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/blob/production/src/main/resources/xsd/place.xsd#L262) there are three types of affiliations for a place event:

- `placeEventAffiliationTypes:lineage`
- `placeEventAffiliationTypes:corporation`
- `placeEventAffiliationTypes:office`

but the owl file only has `:Tradition` as Domain (which corresponds to the first case). Should the other two cases be ignored?

**Comment by xristy** [comment]
ignore corporation and office. They are never used in the data and the ontology includes only :placeEventAffiliation with range :Tradition.
