### ISSUE TITLE
admin prefix

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#17]
It seems either Jena or jsonld-java (I suspect the latter but I need to inspect further) doesn't like the root prefix being included in the admin prefix, I'm getting weird output like

```json
{
  "@graph" : [ {
    "admin/place_town_ch" : "蔡公堂乡",
  } ],
  "@context" : {
    "@vocab" : "http://purl.bdrc.io/ontology/",
    "" : "http://purl.bdrc.io/ontology/",
    "adm" : ":admin/",
    "bdd" : "http://purl.bdrc.io/data/",
    "bdr" : "http://purl.bdrc.io/resource/",
  }
}
```

**Comment by eroux** [comment]
fixed (was a config problem, not really about the schema)

**Comment by eroux** [comment]
https://github.com/jsonld-java/jsonld-java/issues/200

**Comment by eroux** [comment]
I really thought the thing was looking ugly, so I tried to fix jsonld-java, but the problem is deeper: https://github.com/json-ld/json-ld.org/issues/526 so maybe we could change the prefixes and add a `core/` for the main thing? wdyt?

**Comment by xristy** [comment]
why not just leave bdo alone and change admin to:

xmlns:admin="http://purl.bdrc.io/admin/"

**Comment by eroux** [comment]
why not yes ok, we need to move tbr too
