### ISSUE TITLE
taxonomy for Tradition

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/owl-schema#18]
Add taxonomy to organize the :Tradition individuals

**Comment by eroux** [comment]
We should probably ask someone more knowledgeable, but in case my 2c are asked, here they are:

I'm not sure we can do that in a proper way, as these individual cover (at least) two orthogonal concepts which could be called lineage and school, and they even add more complexity by adding "Rime", which fits in neither...

I guess one way to sort the schools would be:
- Sakya
- Nyingma
- Geluk
- Kagyu
- Bodong?
- Jonang
- Bon

but I'm not sure how Chod, Rime or Shangpa Kagyu would fit (Shangpa Kagyu is practiced in both Kagyu and Jonang, but maybe that's not a problem...)... and would we also add the NKT and Shambhala?

Another way would be with [Kongtrul's taxonomy](http://www.rigpawiki.org/index.php?title=Eight_practice_lineages), adding Bon, but we would be missing two individuals (Three Vajras and Kalacakra, or would it be Zhalu?).

I think the only consensual part of the taxonomy would be the taxonomy of the Marpa Kagyu schools... so I'm not sure, maybe we could have two taxonomies, or dissociate the individuals between two types (school and tradition)?

**Comment by xristy** [comment]
You raise relevant points; however, let's maintain the simple (if confused) taxonomy that is currently in use for now. One objective at this point is to demonstrate how we can model taxonomies and another objective is to transfer over what is in use. 

There is a significant collection of discussions that can be had regarding what should be lumped together and what should be separate and what uses these taxonomies are to be put to and so on.

**Comment by eroux** [comment]
for the current taxonomy, are you talking about [this](https://www.tbrc.org/#!persons/tradition)? Interestingly, this exactly matches my proposal for schools, but it only has this level, it doesn't show the sublevels. I guess they are recorded somewhere though, in order for the search to be complete, but I'm not sure where to search? [O5TAX003](https://www.tbrc.org/xmldoc?rid=O5TAX003) is flat too...

**Comment by xristy** [comment]
You're correct that [O5TAX003](https://www.tbrc.org/xmldoc?rid=O5TAX003) is flat. At one time the various sub-schools of Kagyu were underneath Kagyu but it looks like Jeff and Michael ended up with a flat enumeration.

**Comment by xristy** [comment]
I should mention that my recollection of how this list came about was to support the place event affiliation information, most of which was derived from the import of historical Tibetan monastery place information by Karl Ryavec. There the interest was primarily in recording the tradition that was dominant in the founding, rebuilding or conversion of a monastery. So I'm not sure Shambhala or NKT would be needed for this purpose. I chose the name _Tradition_ as a hopefully neutral way of naming a mixed bag. Once again it seems that there is a need for multiple ways of organizing various collections of concepts.

**Comment by eroux** [comment]
Note that ToL has a [tradition taxonomy](http://treasuryoflives.org/tradition) that is:
- closer to the notion of lineage than the notion of school
- merges Zhije and Chod (which I think makes sense... are there a lot of Zhije specific places in the data?)
- add RaLuk, Orgyen Nyendrup, Lamdre and Kalacakra (which also makes sense to me)

But these are related to persons more than places...

**Comment by xristy** [comment]
Is it ok to leave the list of Traditions as is for now? This can be a lively source of discussion among various interested parties.

**Comment by eroux** [comment]
Well, I'm not really sure what the stakes are actually, I'm tempted to see no stakes for now, so it should be ok yes... at the same time, I really feel we could make a tree of the Marpa Kagyu schools (all Kagyu schools except Shangpa Kagyu), as I think this is quite consensual...
