### ISSUE TITLE
standardization of Canonical references

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#2]
Not a crucial point, but we could rename properties related to references to tengyurs to match [standardized references](http://www.rigpawiki.org/index.php?title=Kangyur_and_Tengyur_Sigla) used in other places (Hackett, etc.). So we could for instance rename `work_otani_beijing` into `workTengyurQNumber` or so.

**Comment by xristy** [comment]
Maybe `:workKaTenSiglaQ`?

FWIW: There's an [even larger list of sigla](https://www.istb.univie.ac.at/kanjur/xml4/sub/sigla.php) that might be considered.

The `:work_otani` and `:work_otani_beijing` are the same so we need only use one of them. For now I am removing `:work_otani_beijing`.

I see from the [rigpawiki](http://www.rigpawiki.org/index.php?title=Kangyur_and_Tengyur_Sigla) that sigla `Q` and TBRC `otani beijing` is listed as "Peking 1737 printed Kangyur", while the usages in the current data are all Tengyur:

    O2MS16391 Otani  W1PD95844 bstan 'gyur (dpe bsdur ma)

    O2DB75712 otani beijing  W22704 bstan 'gyur (snar thang)
    O00CR0008 otani beijing  W23702 bstan 'gyur gser gyi lag bris ma (gser bris ma)
    O1PD181215 otani beijing  W1KG13126 bstan 'gyur/ (pe cing /)

    O4JW333 Otani (used on only 1 node)  W22084 bka' 'gyur (sde dge par phud)
    O1JC11494 Otani (used on only 1 node) W22084 EDITING O4JW333 is the preferred for 84000 project??

    O00CR035009 otani beijing  W22704 WITHDRAWN

I'm not sure whether naming the properties by the sigla is helpful. I suspect that for cataloguers the editing tool will need to present something like an informative tool tip along with the sigla character in a dropdown menu. Generally only the s/w and you and I and perhaps a few others should actually be confronted with the property name in the owl file.

**Comment by eroux** [comment]
The more complete list is interesting, thanks! Maybe it should be referenced in the owl file somewhere?

I agree the properties names will never be shown in the editor, but we have an opportunity to make them consistent and clean, so I think it's a good idea to take it... That will make the ontology more appealing to other projects.

**Comment by xristy** [comment]
The various reference numbers have been renamed as below and documentation added

    :workKaTenRefrKTs
    :workKaTenRefToh
    :workKaTenSiglaBon
    :workKaTenSiglaD
    :workKaTenSiglaG
    :workKaTenSiglaH
    :workKaTenSiglaN
    :workKaTenSiglaQ
    :workKaTenSiglaS
    :workKaTenSiglaU
    :workKaTenSiglaZ
    :workRefChokLing
    :workRefIsIAO

The `:workKaTenRef`s are not strictly sigla since they refer to standardized numbering schemes not particular KaTen works.

The ` :workKaTenSigla`s refer to specific KaTen per the [rKTs list of sigla](https://www.istb.univie.ac.at/kanjur/xml4/sub/sigla.php).

The `:workRef`s are reference schemes that are not related to KaTen.
