### ISSUE TITLE
more generic location?

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#20]
Not an emergency, but the only ways to make a reference to a location are currently:
- `workBeginsAt`
- `workEndsAt`
- `lineageLocation`

I think the last one could be replaced with a generic `location`, as we will certainly want to use locations in more and more places in the future, for provenance... wdyt?

**Comment by xristy** [comment]
renamed to :workLocation w/ additional rdfs:comment
