### ISSUE TITLE
volumeQcPerson linking to user account?

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#22]
Should we treat `volumeQcPerson` in the same way we treat `log_who`, by pointing to a user account? It seems there is quite a lot of creativity in the field (more than in the `log_who`, but that shouldn't be too complex... I think it would be a good idea, wdyt?

**Comment by xristy** [comment]
This is not necessary. The qcPerson is very stale and was not maintained past 2003. The qcPerson, qcDate, qcNote and volumeScanVenue have been moved to admin ns and likely can be dropped from the data later.
