### ISSUE TITLE
licences

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#23]
I see a few possible improvements on the licenses:

- maybe the type `WorkLicense` could be generalized to be `License`, as they are not specific, and could be applied to some datasets, items, images, etc. and we could differentiate the copyright on the text, the edition, the scans, etc. all these can be different
- the name `copyrighted` is, I believe, a bit misleading, as a work under the `CCBY` license is also copyrighted (otherwise it would be public domain, not CC-BY). I think `AllRightsReserved` would be more accurate

In fact a more accurate way to describe these would be:

- replace `?a :workLicense bdr:CC-BY` by
   - `?a :contentLicense bdr:PublicDomain`
   - `?a :editionLicense bdr:PublicDomain`
   - `?a :scansLicense bdr:CC-BY`
- replace `?a :workLicense bdr:Copyrighted` by
   - `?a :contentLicense bdr:PublicDomain` or `?a :contentLicense bdr:AllRightsReserved` (that depends)
   - `?a :editionLicense bdr:AllRightsReserved`
   - `?a :scansLicense bdr:CitationException`

but that can be for another time... I can rephrase a little bit the descriptions if you want, that's a domain I enjoy...

**Comment by xristy** [comment]
This is an interesting discussion, but for now the :workLicense reflects BDRC policy and as there are changes to the policy we will revisit.

**Comment by eroux** [comment]
Ok, then maybe changing `:workLicense` to `adm:tbrcLicensePolicy` would make the meaning more explicit?

**Comment by eroux** [comment]
In fact, a good solution for the future would be to have some fields like 
- `:workCopyrightStatement`
- `:workCopyrightDate`
- `:workCopyrightOwner`
- `:workCopyrightCommonWork` (a boolean representing the fact that the copyright is collective and not for a single person, as this changes the span of the copyright)

that would allow some automatic computation of the license for different countries... but that's not for now.

**Comment by xristy** [comment]
Moved :workAccess and :workLicense to annotation properties in latest commit

**Comment by eroux** [comment]
Thanks! Now I'm a little bit confused, how would you think we could define an admin property (in the admin NS) and an annotation property? We may not have to do that now (maybe when things settle down, after the holdings thing), but that's certainly something to clarify

**Comment by eroux** [comment]
With latest license developments, I think this is not necessary anymore, or at least it can be delayed sine die.
