### ISSUE TITLE
encoding of lineage/description@type=summary

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#24]
in [this example](https://www.tbrc.org/xmldoc?rid=L8LS14115) there is a `<lineage:description type="summary">`, how can I encode that?

**Comment by xristy** [comment]
latest commit has :summary replacing :workSummary and adds :Topic, :Lineage and :Taxonomy, all of which could have summaries. It's not clear whether there should be a summary for a Place, Person, Role or Coproration

**Comment by xristy** [comment]
now have removed :summary and :workContents in favor of rdfs:comment (see comment in ontology on rdfs:comments)
