### ISSUE TITLE
how to encode some work properties

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#25]
I have some difficulties encoding:

- `work/info@number`
- `work/info@parent`

what should I use?

**Comment by xristy** [comment]
The w:info/@number is redundant with mw:seriesNumber, which is preferred - :workSeriesNumber.

The w:info/@parent should be mapped to either :workExpressionOf or :workNumberOf depending on whether w:info/@number is present together with the w:info/@parent

**Comment by xristy** [comment]
The @parent for for all Works with @number are now marked as released and @nodeType="series" with @parent="W99LEGACY" to help find them after migration
