### ISSUE TITLE
what to do about External?

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/owl-schema#26]
The `external` element in common.xsd needs to be mapped. The initial idea would be to `rdfs.seeAlso` but there's an `@source` and `@data` pair of attrs in the XML so what to do?

**Comment by xristy** [comment]
For the `<?:external/>`s the `@data` is a URL and the `@source` is not present or extraneous.

There are 13 `<place:external/>`s with `@data` holding a URL. 3 of these are tbrc.org URLs and the rest are to Treasury of Lives (ToL).

There are 1015 `<person:external/>`s with `@data` holding a URL. Of these, 995 appear to be references to ToL and the other 15 are tbrc.org URLs. Some of these are Outline nodes others whole Works. These ideally should be converted to the bdr:Wxxxxx resource URIs that the Outline nodes or Works get mapped to. The ToL URLs seem fine.

There are 0 externals in Works, Outlines, Offices.

There are 10 externals in Lineages which are all tbrc.org URLs.

There is 1 ToL reference in Corporations

There are 2 externals in Topic, both are non tbrc.org

**Comment by eroux** [comment]
If it's that consistent, I think the best solution is:

- for tbrc URLs, do something like `?a rdf:seeAlso bdr:W123` (coping with the fact that outlines now have different IDs will be the most difficult part)
- for ToL URLs, add a new annotation property `:seeAlsoToL` having any url as range

I think that would make the cleanest organization... It would be really great if ToL was using linked data... maybe they would be interested if I send them my small document? do you have a contact?

**Comment by eroux** [comment]
I've done that

**Comment by xristy** [comment]
Yes I intend that tbrc.org URLs be mapped to `?a rdfs:seeAlso bdr:XXXXX`. I see no need to single out ToL for special treatment in the ontology. I think `rdfs:seeAlso` is quite sufficient.

**Comment by eroux** [comment]
ok
