### ISSUE TITLE
Migrating Fragile Palm Leaves info

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/owl-schema#27]
There are three `<w:description/>`s on the various FPL works with types: `id`, `remarks` and `room`. This data is part of the larger Holdings issue. It seems that all of this information needs to be associated with a physical holding similar to that used for the Tibetan Library Manager (TLM).

In the TLM there is a shelf code made by joining a list of codes from a Subject Headings Taxonomy designated by the library. So we see shelf marks like "ཁ|མ|༥|4278" where the first three items are the codes of the hierarchically organized subject headings and the 4278 is an accession number assigned by the librarian when cataloging. The physical library is organized in terms of the subject headings taxonomy so users are able to locate works by following a map of how the subject headings have been laid out in space. The accession n umber serves to indicate the particular item on a shelf

In the case of the FPL collection the shelf mark would be like formed by concatenating the room and the id like: "3A | 110". So the TLM shelf and the FPL room+id can be represented in the same way.

That leaves the remark which is a description of the appearance of the physical object such as "Red lac. covers. Gilded leaves with vermilion band.". Is there any reasonable correspondence with TLM?

**Comment by xristy** [comment]
the `<w:description type="remarks"/>` is handled by adding a `:note` to the `:ItemPhysicalHolding`.

Since each FPL has a Work and two Items it suffices to append a suffix to the base Item id:

For Work bdr:Wxxxxx the Items are bdr:Ixxxxx_01 and bdr:Ixxxxx_02.

This approach can also be used with TLM holdings since there are many works that have a holding the the main Dzongsar library and in the shedra library which are two different libraries.

It might be a nice convention to make all Items have a suffix so even the digital asset for W12827 would be I12827_01.

**Comment by xristy** [comment]
After some reflection I've added `:volumePhysicalDescription` to represent the FPL remarks. This is much clearer and consistent with Library practices

**Comment by eroux** [comment]
A little bit of clarification is necessary on the `remarks` field: the property `:volumePhysicalDescription` has a `Domain` of `:VolumePhysicalAsset`, but states:

```
Migration hint: for FPL Works map the <work:description type="remarks"/>to :itemPhysicalDescription with string with language tag "en"
```

which is quite confusing... I think it should be renamed `itemPhysicalDescription` and have a domain of `:itemPhysicalAsset`, wdyt?

**Comment by xristy** [comment]
I'll fix the documentation. I meant for the _physical description_ to be on the`:VolumePhysicalAsset` since there could be a multi-volume situation with different descriptive remarks

**Comment by eroux** [comment]
Hmm... so that means that for each FPL Item I create something like:

```
bdr:W1FPL110
    a :Work;
    :workHasItem bdr:I1FPL_002.

bdr:I1FPL_002
    a :ItemPhysicalAsset
    :itemHasVolume bdr:I1FPL_002_V001.

bdr:I1FPL_002_V001
    a :VolumePhysicalAsset
    :volumePhysicalDescription "Red lac. covers. Gilded leaves with vermilion band.".
```

?

**Comment by xristy** [comment]
Pretty much. What I've put in the google doc is like:

    bdr:IW1FPL110_01 a :ItemPhysicalAsset ; :status bdr:StatusReleased ;
        :itemForWork bdr:W1FPL110 ;
        :itemLibrary bdr:G1TLMFPL000001 ;
        :itemShelf “3A | 110” ;
        :itemHasVolume [ a :VolumePhysicalAsset ;
            :volumeNumber 1 ;
            :volumePhysicalDescription “Red lac. covers. Gilded leaves with vermilion band.”@en ] .

I guess there's a question of whether to use a blank node for the volume or not.

**Comment by eroux** [comment]
Ok, I can use blank nodes for now, I'll change the code accordingly
