### ISSUE TITLE
removing the workPubinfoSeries type?

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#28]
Changing the code with what we discussed yesterday left me in a very puzzled state, as the pubinfo series number is not written in the `bdo:Work`, but in a sub node called `bdo:WorkPubinfoSeries`... But I guess there can only be one of these nodes, so for the sake of simplicity and consistency, we can probably just remove it and write the different properties (`:workSeriesNumber`, `:workSeriesContent` and `:workSeriesName`) to the `:Work` object directly?

**Comment by xristy** [comment]
Thanks. I had overlooked those.
