### ISSUE TITLE
locations

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#29]
Instead of having `:workLocationFF`, in the same spirit but more generic, maybe we could have `:workLocationEndPage` and `:workLocationEndVolume`? That would prevent the need for two very different modelings corresponding to the general case and the case where a location spans several volumes... wdyt?

**Comment by xristy** [comment]
This implies also `:workLocationEndSide`, `:workLocationEndLine`, `:workLocationEndPhrase`.

**Comment by eroux** [comment]
oh, I forgot those, why not yes
