### ISSUE TITLE
notLocation instead of noteLoc

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#3]
the data property linking a `Note` to a location as a string is named `noteLoc`, while all other properties linked to location seem to have the full `Location` in their name (`workLocation*` for instance). Maybe it should be renamed `noteLocation`? or maybe `Loc` means a string instead of a `Location`? In this case I think the convention is quite unobvious, maybe `noteLocationString` would be better?

**Comment by eroux** [comment]
Ok,maybe it could have an annotation indicating that this is just temporary and solely for the sake of saving bogus data during the migration? Maybe something like `owl:deprecated "true"`?

**Comment by xristy** [comment]
the :noteLoc changed to :noteLocationStatement and moved to annotation property along with :noteWork and :noteText
