### ISSUE TITLE
other outline properties

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#33]
A few other outlines properties will need a differentiation when attached to a work:

- `rdfs:seeAlso` (formerly external)
- `:note`
- the [various properties](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/blob/production/src/main/java/io/bdrc/xmltoldmigration/CommonMigration.java#L240) corresponding to `description`, or maybe they could be filtered...
- the `location` of the root node of an outline, but maybe this can just go away?

**Comment by eroux** [comment]
Also, what is the property to encode the old outline RID?

**Comment by xristy** [comment]
I'm adding Class `admin:Outline` and `admin:outline` AnnotationProperty `:Work -> :admin:Outline` then attach all items such as `rdfs:seeAlso` and so on to instance of `admin:Outline`.

Use `:workLegacyNode` on `admin:Outline` to record the old outline RID - I've added `admin:Outline` as a domain for `:workLegacyNode`.

**Comment by eroux** [comment]
I think `:workLegacyNode` could be qualified as part of our administrative data to run the website instead of a general Buddhist Digital Ontology property, so I think it could have its place in the `admin` namespace?
