### ISSUE TITLE
outline types

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#34]
A property linking a `:Work` (or maybe just an `:Outline`?) and an `:OutlineType` is still missing

**Comment by eroux** [comment]
There is another type that we cannot currently capture, it's the `node@type` value, the different possibilities are listed [here](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/blob/master/src/main/resources/xsd/outline.xsd#L291)

**Comment by xristy** [comment]
the node@type is captured via `:workPartType`

**Comment by eroux** [comment]
ok perfect!
