### ISSUE TITLE
using typed integers?

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#35]
Should we keep xsd:positiveInteger instead of xsd:integer in the data?

A few info I gathered this morning:
- Fuseki converts all integer types to `xsd:integer`, so query results don't know the original type (all come as xsd:integer, I did a small test)
- When using [JSON native types](https://www.w3.org/TR/json-ld-api/#rdf-to-object-conversion), only xsd:integers get converted
- it's quite easy to figure out if an integer is positive or not, and SHACL has some rules to [define a range](https://www.w3.org/TR/shacl/#core-components-range)

If we keep the type, jsonld documents will look like

```json
"workNumberOfVolumes" : {
  "@type" : "xsd:positiveInteger",
  "@value" : "1"
},
```

instead of

```json
"workNumberOfVolumes" : 1
```

based on that I propose to make the ranges xsd:integer all the time and to use SHACL rules in the future to check some ranges. wdyt?

**Comment by xristy** [comment]
+1 I'll make the changes in the owl doc

**Comment by eroux** [comment]
Reopening for 3 more properties: `volumePagesIntro`, `volumePagesTbrcIntro` and `volumePagesText` have `xsd:nonNegativeInteger` as Range.
