### ISSUE TITLE
moving TLM properties

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#4]
I think the TLM administrative properties should be in a separate entity as the rest of the cultural heritage ontology. Maybe something like

```
bdr:TL0123 a :TLMLibrary;
   rdfs:label "this or that place";
   tlm:email "admin email";
   tlm:place bdr:G123;
   etc.
```

?

**Comment by xristy** [comment]
In the latest ontology I've moved the various _TLM_ data properties to the admin ns and made them annotation properties
