### ISSUE TITLE
desc_noType

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#44]
I think the last big source of puzzlement I have regarding the migration is how to migrate descriptions with no type. We currently have `:desc_NoType` which is the last property with a `_` so I guess it's quite unsatisfactory... Maybe I can just migrate to `rdfs:comment` and we can migrate typeless descriptions to generic properties like `rdfs:comment` or `skos:note`? I tend to prefer the former... wdyt?

**Comment by xristy** [comment]
rdfs:comment seems fine to me. Perhaps append " - was description with no type" or some such

**Comment by eroux** [comment]
ok
