### ISSUE TITLE
mappings for some place types

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#45]
There are a few place types I'm not sure how to map:

- `placeTypes:townshipSeats`
- `placeTypes:rgyalKhams`
- `placeTypes:traditionalPlaceName`
- `placeTypes:residentialHouse`

What should there be mapped to?

**Comment by xristy** [comment]
- `placeTypes:townshipSeats`
     ==> `bdr:PlaceTypeShang`
- `placeTypes:rgyalKhams`
    ==> `bdr:PlaceTypeRgyalKhab`
- `placeTypes:traditionalPlaceName`
      ==> `bdr:PlaceTypeSrolRgyunGyiSaMing`
- `placeTypes:residentialHouse`
     ==> `bdr:PlaceTypeGzimsKhang` (house)

**Comment by eroux** [comment]
Thanks, I've changed the migration accordingly
