### ISSUE TITLE
missing item -> etext properties

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#46]
In the current migration, I link etexts in items through the following pattern:

```ttl
    :itemHasVolume      [ :volumeHasEtext     [ :eTextResource      bdr:UT21019_001_0001 ;
                                                :seqNum             1
                                              ] ,
                                  [ :eTextResource      bdr:UT21019_001_0009 ;
                                    :seqNum             9
                                  ] ;
                          :volumeNumber       1
                        ] ,
```

but the `:volumeHasEtext` and `:etextResource` are missing from the ontology... note that I'm not entirely sure what is the type of the blank node which is the subject of `:etextResource`...

**Comment by xristy** [comment]
I've added `:volumeHasEtext`, `:eTextResource`, and `:EtextRef`. I also corrected the range of `eTextInItem` to `:ItemEtext`.

The pattern should look like:

    bdr:I21019_E01 a :ItemEtext ;
      :itemHasVolume      
          [ a :VolumeEtextAsset ;
            :volumeHasEtext     
              [ a :EtextRef ;
                :eTextResource  bdr:UT21019_001_0001 ;
                :seqNum  1 ] ,
              [ a :EtextRef ;
                :eTextResource  bdr:UT21019_001_0009 ;
                :seqNum  9 ] ;
            :volumeNumber  1 ] ,

**Comment by xristy** [comment]
Sorry forgot to auto-close with the commit
