### ISSUE TITLE
encoding biographies

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#48]
I'm not sure the best way to indicate that a work is a biography of a person. Currently we have `workIsAbout` which has no domain nor range but only topics as examples. Should we use that? Or maybe make a subproperty `workBibliographyOf`? Maybe it's not useful if we have

```
bdr:W123 :workHasGenre bdr:T123 ;
                 :workIsAbout bdr:P123 .
```

with `bdr:T123` being "namthar". Although one could argue that in this case, the fact that `bdr:W123` is a biography of `bdr:P123` could be fully express by the ontology without relying on user-defined genres, as it's an important data... but we can leave that for later as it's unlikely to change the migration.

**Comment by xristy** [comment]
I think we're almost there, I think.

Checking `bdr:W20443` I see:

    bdo:workIsAbout bdr:P4252 ;
    bdo:workIsAbout bdr:T3 ;

 which came from:

    <w:subject type="isAboutPerson"  class="P4252">dbang phyug brtson 'grus</w:subject>
    <w:subject type="isInstanceOfGenre"  class="T3">rnam thar</w:subject>

so if the `@type="isInstanceOfGenre"` is mapped to `bdo:workGenre` then:

    bdo:workIsAbout bdr:P4252 ;
    bdo:workGenre bdr:T3 ;

and all is good?

**Comment by eroux** [comment]
oh thanks, I just fixed that. 

In the piece of code where the bug was, I realize there was a grey area: how should I encode `@type="isCommentaryOn"`? 

I suppose using `:workIsAbout` is necessary, but maybe I should add a `:workGenre` linking to the appropriate topic? If so, which one would that be? 

In a perfect world, an xml file with `@type="isCommentaryOn"` has a `@type="isInstanceOfGenre"` with the appropriate commentary type, but my suspicion is that it's not always the case...

**Comment by xristy** [comment]
In looking at the data I see there are two cases: 1) `W1KG12097` where the genre is a commentarial type, in this case `T132` ('grel pa), there are also `T61` (rnam bshad) and so on; and 2) `W20400` where the genre is more like a tradition or school, in this case `T2055` (sems tsam/cittamatra).

The first case is simple:

    bdo:workGenre bdr:T132 ;
    bdo:workIsAbout bdr:W20804 ;

In the second case adding:

    bdr: W20400 bdo:workGenre bdr:T132

to stand-in for the (now implicit) "isCommentaryOn" would perhaps be appropriate.

There's another sort of type 1 situation: `W20401` which has:

    <w:subject class="T233"  type="isAboutUncontrolled">dbu ma</w:subject>
    <w:subject class="T132"  type="isInstanceOfGenre">'grel pa </w:subject>
    <w:subject class="W19458"  type="isCommentaryOn">madhyamakavatara </w:subject>

which I think just maps to:

    bdo:workGenre bdr:T132 ;
    bdo:workIsAbout bdr:W19458 ;
    bdo:workIsAbout bdr:T233 ;

There may be other cases to consider out of the 970 occurrences of `isCommentaryOn` that I haven't found yet.

The commentary topics that I am aware of are:

    T304         mchan 'grel

    T3JT5054     don 'grel

    T61          rnam bshad

    T4JW5424     rang 'grel

    T10MS12837   dgongs 'grel

    T132         'grel pa

    T1488        'bru 'grel

    T1491        dka' 'grel

    T2397        tshig 'grel
