### ISSUE TITLE
Linking to lexvo ?

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#49]
I think instead of defining our own languages and scripts, maybe we could just link to [lexvo](http://www.lexvo.org/)? Example: [bo](http://www.lexvo.org/id/iso639-1/bo) (with a `sameAs` to [bod](http://www.lexvo.org/id/iso639-3/bod)) and [Tibt](http://www.lexvo.org/page/script/Tibt)). A few notes:

- when opening the [lexvo rtf file](http://www.lexvo.org/resources/lexvo_2013-02-09.rdf.gz), Protege complains about an invalid character (present many times in the document), not sure why this happens, but it seems easy enough to fix and provide upstream with a patch
- the main problem with the complete lexvo rtf file is its size (70MB uncompressed), we clearly don't need all this, but we do need things that will require some distillation work on our side:
  - the base vocabulary
  - a reasonable extract with the languages we're using, to feed the BLMP with, so that it can work offline
- lexvo doesn't contain transliterations (not really a problem, just a remark)
- this would not affect the LangScript class
- lexvo doesn't contain some scripts we need (ume and uchen), but if we define them with the same vocabulary, that shouldn't be a problem

wdyt?

**Comment by xristy** [comment]
I've added `owl:sameAs` to `:Language`, `:Script`, and the various individuals of `:Language` and `:Script` to refer to various items of [lexvo.org](http://www.lexvo.org)
