### ISSUE TITLE
defining user accounts

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#5]
We should start to think about user accounts and how we will handle the link between the data and the users. A few ideas:

- data about user accounts should not appear in a public git repository. In fact, under European laws, I don't think they should appear in any git repository because we should be able to erase them permanently at the request of a user
- maybe we don't need anything more than `foaf` to represent the data? In which case `log_who` could have `foaf:Agent` as its domain?
- I can extract all names appearing in `log_who`s and map them to some IDs, we don't have to actually create the profiles now

wdyt?

**Comment by xristy** [comment]
I update the ontology to include foaf:Agent, added objectProperty :logWho with range foaf:Agent, renamed :log_content to :logMesage, :log_when to :logWhen, and :log_entry to :logEntry.

**Comment by eroux** [comment]
I've added a few questions in the [list](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/blob/production/src/main/java/io/bdrc/xmltoldmigration/CommonMigration.java#L96), I guessed the similarity in some accounts, but I'm not really sure for some
