### ISSUE TITLE
reviewing the changes I made

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#50]
@xristy you can review the changes I made here, after looking at some books, I realized that when in the `encoding` field I have:
- `mongolian`, this can mean
  - mongolian in cyrillic
  - mongolian in old script ([ex](https://www.tbrc.org/#library_work_ViewInWIndow-W00KG09211%7CI00KG09359%7C1%7C1%7C1%7C870))
  - mongolian translitterated in latin script ([ex](https://www.tbrc.org/#library_work_ViewInWIndow-W1KG15037%7CI1KG15076%7C1%7C1%7C1%7C214))
- `sanskrit` can be in
  - devanagari
  - iats transliteration
  - tibetan script (all cases seem to happen)
- `chinese` could be in simplified chinese (`Hans` script) or traditional (`Hant` script) but I have no idea how to discriminate between the two

so I can't really map `chinese`, `sanskrit` and `mongolian` to a fully detailed `:LangScript` (with `:language` and `:script` filled), that's why I created the various `Unknown` variations (`bdr:SaUnknown`, etc.), with no associated `:script`. I think these may be the root nodes if we build a LangScript taxonomy... wdyt?

**Comment by xristy** [comment]
The various additions look good to me. Since "mongolian in old script" is mentioned, is there a "mongolian in new script"? All of the material in the archive that I'm aware of is in Mongolian script of some flavor (not Cyrillic or Latin). 

I guess that `bdr:SaUnknown` would make a plausible root. Would `bdr:SaUnspecified` work for you? I've tended to think of "Unknown" as not available to be entered, and "Unspecified" as we could know it by looking/reading but we haven't yet done that.

**Comment by eroux** [comment]
My understanding is that the cyrillic script is the official one since the 1940s, but I have a very small knowledge of this topic; so in my mind "old" refers to "before the 1940s"). Maybe "old script" should be replaced by "mongolian script", it would be more neutral I think...

No problem for `Unspecified`.

**Comment by xristy** [comment]
There are 38 Works with Mongol encoding. Two that might be of interest as examples of using the LangScript properties:

[W00KG09211](https://www.tbrc.org/#!rid=W00KG09211) is a mix of Tibetan DBuChen and Old Mongolian.

[W00KG03892](https://www.tbrc.org/#!rid=W00KG03892) is a Mongolian grammar in Cyrillic with Old Mongolian. It's not a very good copy and the images are apparently rather large. It's not clear whether it is a Mongolian grammar in Russian or a grammar of Old Mongolian in Modern Mongolian...

**Comment by xristy** [comment]
Am I correct that `bdr:BoTibt` would be a plausible root for the Tibetan portion of a LangScript taxonomy? Is `bdr:ScriptTibt` essentially saying "generic" Tibetan script?

**Comment by eroux** [comment]
W00KG03892 is a bit disturbing actually...
- I do not know where Tibetan title comes from, it seems like a very bad practice to make up titles like that... especially since "mongolian grammar in Russian" in English would certain have been more helpful than "Mongolian Grammar treatise" translated in Tibetan... but I think "грамматика монгольско калмыцкаго яэыка" would have been best, even better than the phonetics "grammatika mongol' sko-kalmytskago iazyka" of the work data. Note that the title indicates "mongolian-kalmuk", but I'm not sure how close the two languages are...
- it is in the "Tibetan Grammar" category on the website although it's a Mongolian grammar in Russian...
- the encoding specified is mongolian, but the text is in russian... although this may not be obvious for someone who doesn't read cyrillic (I barely can but I'm pretty sure this is Russian), but the date (1819) should be a string indication that the text is in Russian, as mongolian texts of this period would be, I think, in mongolian script.

yeark... let's not look too close at the data...

For the Tibetan, I'm not sure... I agree it's tempting to have `BoTibt` as root at it seems the "normal" Tibetan, but at the same time it also seems strange to have `BoEwts` as a subclass... but not too strange maybe, I don't really have a strong opinion on that!

**Comment by xristy** [comment]
I was fishing for whether you were thinking of `bdr:BoTibt` as parallel to `bdr:SaUnspecified` or whether there should be a `bdr:BoUnspecified`. I really think that the `bdr:BoTibt` should be considered parallel to `bdr:SaUnspecified` and I don't find it strange to have `bdr:BoEwts` under `bdr:BoTibt` any more than `bdr:SaIast` under `bdr:SaUnspecified`
