### ISSUE TITLE
Autograph manuscript type

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#55]
It may be useful to record that a manuscript is an autograph manuscripts, as these would be something we would certainly like to communicate on and find easily.

We may not have many (if any?), but will certainly have some in the future (at least one I'm thinking about)...

**Comment by eroux** [comment]
Actually there is another feature of the same kind we may want to record: the first printing of a xylograph, like the one we have of the Dergue Kangyur, this is something scholars see as an important information

**Comment by xristy** [comment]
I agree that we need a simple means of denoting and parmas, e.g. W4CZ5369, W4CZ5370, or W4PD3142; and autographs, e.g. W8LS16443 and W8LS16235.

**Comment by xristy** [comment]
ooops! I was asleep and blithered on printers instead of first printings. In any event I'm adding bdr:PrintTypeParPhud, for use with W22084, and bdr:PrintTypeAutograph, for use with  W8LS16443 and W8LS16235.
