### ISSUE TITLE
order hasPart property

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#58]
We currently record that a work is part of another, but we don't record the order of the work parts, and we certainly should. I don't know how BIBFRAME, etc. solved this.

**Comment by xristy** [comment]
`:workPartOf` should be accompanied by an appropriate `:workLocation` and sorting the collection of parts by location gives the order.

However, that's pretty contorted so I agree that it would be helpful to have a simple index for both `:workPartOf` and the inverse `:workHasPart`

**Comment by eroux** [comment]
I agree `:workLocation` should be enough for now (although many non-leaf nodes don't specify it in our outlines), but it would be good to have a simple index as you say, especially since there's no location information for abstract works and we may want to specify some parts of it

**Comment by eroux** [comment]
fixed by https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/deca721af5f901f8994269a4b45f77d85e2d67ee
