### ISSUE TITLE
mongolian title

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#61]
some editions of the Kangyur have a Mongolian title on the Title page. I'm not sure if the title is translitterated (from Sanskrit or Tibetan) or translated, but I'm wondering how we should record that... Would that be something like the `bdo:WorkSanskritTitle` or would it just be a regular title with a mongolian string? rKTs has some mongolian titles, hence the question...

**Comment by xristy** [comment]
Unless we can get a more definitive comment from someone who knows the material then it would seem reasonable to just use the existing title types with the appropriate Mongolian tags

**Comment by eroux** [comment]
I got some answers about that: 

- titles a Mongolian translation, not Sanskrit or Tibetan transliterated in Mongolian
- they are indicated in the same way as Sanskrit or Tibetan titles, at the beginning of sutras (hereafter translated into English): "in Sanskrit fooskt, in Tibetan footib, in Mongolian foomong" (rgya gar skad du ... bod skad du ... etc.)

**Comment by eroux** [comment]
I've migrated the Mongolian titles to regular `bdo:BibliographicTitle`, but now I'm wondering why we have `bdo:WorkSanskritTitle` at all... conceptually it's just the same title, but in Sanskrit, right? we could just map it to `bdo:WorkBibliographicTitle`...

**Comment by eroux** [comment]
well, it seems the `bdo:WorkSanskritTitle` is an interesting hallucination on my side...
