### ISSUE TITLE
domain for :onOrAbout

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#62]
It would be helpful for the BLMP to have a domain for `:onOrAbout`, I think the union of `:PersonEvent`, `:PlaceEvent` and `:LineageReceived` would be reasonable?

**Comment by xristy** [comment]
Good suggestion. [Fixed](https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/9f1269a0c9dd1cc94c96e5eea761382e9f4fe325).

**Comment by eroux** [comment]
Thanks! The BLMP will have difficult time understanding this kind of OWL pattern though, I'm wondering if it would make sense to have something like:

```
:Facet
├─ :Event
│  └─ :PersonEvent
│  └─ :PlaceEvent
│  └─ :LineageReceived
...
```
? The BLMP would understand that structure directly.

(actually, maybe it woud make sense to rename LineageReceived into LineageEvent?)

**Comment by xristy** [comment]
[Fixed more][(https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/28ec849765638d5af77ee0b6f93422926ab0c75d)

**Comment by eroux** [comment]
Hmm what about having `:Event` in `:Facet` and not `:Entity`? It would correspond to the current way of thinking of the BLMP (and mine too actually)
