### ISSUE TITLE
recording indicated part names

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#66]
There is an interesting feature in some parts of the Kangyur: we have [vol2 p. 571 l. 6](https://www.tbrc.org/browser/ImageService?work=W22084&igroup=0887&image=573&first=1&last=636&fetchimg=yes) an indication saying "this is the first chapter", but we have [vol2 p. 570 l. 2](https://www.tbrc.org/browser/ImageService?work=W22084&igroup=0887&image=572&first=1&last=636&fetchimg=yes) an indication saying *shA ri'i bu dang maud ga la gyi bu'i le'u*... so it would be like the 0th chapter or something... anyways, because the names of all the chapters are just "chapter number X", it would be interesting to semantically indicate that with an integer (in addition of the name) so that it can be translated in various languages, but as it's not completely correlated with the actual order of the parts, an additional property would be required?

**Comment by ngawangtrinley** [comment]
These aren't actual chapters! What you called chapter 0 is a different content than what comes after, if you look at the numbered "chapters" you'll see that the first two are those of _sHa ri'i bu_ and _maud gal gyi bu_. Here the 36 "chapters" are accounts/stories told by arhats describing the karma that brought them there, so _le'u_ here is more of a story than a chapter. Something like _thus goes the story of shA ri'i bu_.

**Comment by eroux** [comment]
Iiiiiii see! Thanks, I'll update the migration code accordingly
