### ISSUE TITLE
:notBefore / :notAfter

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#74]
A few partner datasets (CBETA, 84000, etc.) have some indication of lower/upper limit dates for events (translations), while we can always indicate

```
  :onOrAbout "700-711"
```

it seems rather suboptimal, I think having

```
  :notBefore 700
  :notAfter 711
```

would be more straightforward and ease search... We would also maybe have an exact version taking an int instead of a string:

```
  :onExact 700
```

?

**Comment by xristy** [comment]
so you would have it that `<#> :onOrAbout "7??"` or `<#> :onOrAbout "72?"` would be replaced by

    <#> :notBefore 700 ; :notAfter 799 .

and

    <#> :notBefore 720 ; :notAfter 729 .

?

**Comment by eroux** [comment]
I think it would be nice yes

**Comment by xristy** [comment]
first attempt in commit [0dd115e](https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/0dd115e83e9bd7c1c1a34e4858c8dfa62e4c24d5).

**Comment by eroux** [comment]
thanks!
