### ISSUE TITLE
recording time periods

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#75]
I think it would be useful to be able to record time periods as resources. There could be several of them for one event. These could be:

- quarters of century, like on ToL
- dynasties in a Chinese context as on [CBETA](http://cbdata.dila.edu.tw/v1.2/static_pages/time)

The resources could then be organized in taxonomies.

both could be used as facets for the search. If we use the `:notBefore` / `:notAfter` mechanism, these could probably be inferred... but we lack a property to indicate them. Maybe `:inTimePeriod`?

**Comment by xristy** [comment]
[4745ec2](https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/4745ec20e5dcacd89dec89627b471686bc9fb153) added `:eventPeriod` and associated `:TimePeriod` types with example individuals

**Comment by eroux** [comment]
thanks!
