### ISSUE TITLE
work events?

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#76]
I have that at the back of my mind for a while, but I think now is a good time to express it because that would solve a problem I'm facing:

I have date ranges in the EAP spreadsheet but I cannot really express them with the new notBefore/notAfter/onYear properties, because these EAP dates are not associated with events, but are supposed to go in `:workPublisherDate` (I think?). So I'm thinking maybe we could change the model a little bit to have workEvents (authorshipEvent, translationEvent, publicationEvent, etc.) like in the BIBFRAME2 model (although it's not very documented). So we could have something like:

```
bdr:W123
   :workHasEvent [ a :TranslationEvent ;
       :creatorTranslator bdr:P123 ;
       :notBefore 70 ;
       :notAfter 700 ;
   ] ,
   [ a :CopyEvent ; // or publishing? in the case of EAP, someone copied the text by hand, not sure "publishing" really describes that?
     :notBefore X ;
     :notAfter Y ;
   ] .
```

I think we will be able to express more things this way... for example 84000 have date ranges for the translations (CBETA also has that for the Chinese translations), this model would express these very simply, while we can't do that with the current model... what do you think?

**Comment by eroux** [comment]
exactly, I think I was mistaken by the BIBFRAME image:

https://www.loc.gov/bibframe/docs/images/bf2-model.jpg

but the BIBFRAME event is not the same as what I imagine... I was sure to have seen this idea somewhere but I can't find where (doesn't seem to be in RDA neither)...

**Comment by xristy** [comment]
[4745ec2](https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/4745ec20e5dcacd89dec89627b471686bc9fb153) added `:WorkEvent` facet and subclasses

**Comment by eroux** [comment]
great, thanks a lot! just a few labels are missing (and obviously some individuals, but we'll create them as we need them). I was wondering if the :workCreator should / could be linked to an event? I don't have a strong opinion on that...

**Comment by xristy** [comment]
The `:workCreator`, `:workCompletionDate`, `:workDateOfWriting`, `:workPublisherDate`, `:workPublisherLocation`, and `:workPublisherName` are all candidates for normalizing to `:WorkEvents`.

`:workPublisherName` should be considered for generating `:Corporation` resources.

How much of the normalization can be done mechnically in xmltold...?

**Comment by xristy** [comment]
[e7448fc](https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/e7448fc53002cb12e2008cab16caeb7e790298f5) added `:PersonOrCorporation` for use, e.g., with `:WorkPublished` since the `:eventWho` in that case will usually be a `:Corporation` resource rather than a particular `:Person` (this implies creating resources for the Publishers).

There are likely other `:Event` situations that can make use of `:Corporation`, e.g., perhaps a monastery conversion might be recorded as effected by a particular group versus a specific `:Person`.

**Comment by eroux** [comment]
Thanks a lot! I think normalizing `workPublisherDate` and `workPublisherLocation` can be done easily, we can certainly deprecate these two. 

I'll try to normalize the publisher names into corporations, that's probably going to take some time but we can certainly normalize a big part automatically. 

For `workCreator` I'm sure we can move them to events automatically... maybe a few corner cases will be annoying but that's fine. I think the only change would be to change the domain to `:Event`, we still need to differenciate the various actors, because several of them can act on the same event (a translation for instance can have a translator and a pandit).

As for `workCompletionDate` and `workDateOfWriting`... is there a clear semantic difference that has been used consistently in the cataloging or have they both been used for "the date of a work"?
