### ISSUE TITLE
encoding secondary incarnations

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#9]
the `incarnationOf` [element](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/blob/master/src/main/resources/xsd/person.xsd#L154) can have a `secondary` argument. The code uses a `incarnationOf_secondary` relation, but I realize it never reached the ontology (even the old one). What's the best way to encode that?

**Comment by xristy** [comment]
There are exactly five occurrences of @secondary in the data and at least 4 of them are bogus:

- P3CN1582 @relation=NOT PRESENT  @secondary="yangtse"
- P1PD108247 @relation="yangsi" @secondary="yangsi"
- P2MS9536 @relation="mind" @secondary="mind"
- P6610 @relation="speech" @secondary="speech"
- P698  @relation="body" @secondary="general"

For P698 it is sufficient to:

    [ a :PersonIncarnation ;
      :personIncarnationOf bdr:P314 ;
      :personIncarnationOfType bdr:IncarnationTypeBody, bdr:IncarnationTypeBody ] .

FWIW: There are 14 more occurrences of <p:incarnationOf relation="..."/>. There are 1449 occurrences of <p:incarnationOf being="..."/> and a total of 1455 occurrences of <p:incarnationOf/> so there are 6 instances without @being:

P11MS241, P1388, P1457, P2091, P2LS151, P1PD127770

All except P2LS151 are empty <p:incarnationOf/> elements. In the case of P2LS151 the element is:

    <p:incarnationOf>grib tshe mchog gling</p:incarnationOf>

and "grib tshe mchog gling" does not resolve to a person so this should be silently ignored.

**Comment by eroux** [comment]
For P698, is it really worth adding the second type? It seems quite useless and would add some boring code...

**Comment by xristy** [comment]
I think all that is needed, is to say that if there is a valid @secondary it can just be added. In other words no need to distinguish between @relation and @secondary. Just two assertions of `:PersonIncarnationType`.

I'll fix the other 4 records so only P698 will be there.

I'll also remove the empty <p:incarnationOf/> elements from the other 6 resources.

I should have mentioned that when there is no @relation, then the statement:

    :personIncarnationOfType bdr:IncarnationTypeGeneral 

should be added/inferred.
