### ISSUE TITLE
deprecation pattern

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#90]
I think it would be helpful to have the `deprecated in favor of` be a property instead of a free text in the `owl:deprecated` property... I'm not sure how it would be best, but maybe:

```
bdo:creatorPandita
    owl:deprecated true ;
    adm:deprecatedInFavorOf bdo:creatorIndicScholar .
```

would be a good start? We can also imagine a deprecation note, date, log entry, etc. but these could be annotations we could add later. We could also use this pattern for general resources (not just properties).

**Comment by xristy** [comment]
addressed in [commit f5eeeca](https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/f5eeecac46cc645a912be55ac00401ae1b779a78)
