### ISSUE TITLE
LangMARCCode

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#96]
Same as previous issue, it would be convenient to have a property  record the Marc code for a Language (or LangScript, but I think Language is more accurate)

**Comment by xristy** [comment]
@xristy closed this in [df395e1](url
https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/df395e1f189ebf33276cd8c5ca085967c63789ff)
